### PR TITLE
Sonu zkthon

### PR DESCRIPTION
**Pull request by SonuChoud**
## Description

This pull request is for the zkEVM Challenge 2 and 3.

## Checklist

- [ ] I have created a new file named `solution-2.md` `solution-3.md` for this challenge.
- [ ] I have added the details of my submission to the [Airtable form](https://airtable.com/shr21z0FfPImZfYBQ).
- [ ] I have named my branch `sonu_zkthon`.

### CODE REVIEW

**Review by PriyathamVarma — CHANGES_REQUESTED** [review]
Thank you for the participation ser. But as part of the challenge-3 please try to submit the code used to interact with the smart contract.

**Comment by SonuChoud** [comment]
> Thank you for the participation ser. But as part of the challenge-3 please try to submit the code used to interact with the smart contract.

I have burned the token. The token code is same as challenge 2. So I pasted the same code. But I have provided the TXN hash of the token burned. Is it incorrect?

**Comment by SonuChoud** [comment]
> Thank you for the participation ser. But as part of the challenge-3 please try to submit the code used to interact with the smart contract.

Completed

**Review by PriyathamVarma — APPROVED** [review]
Excellent job is done ser.

**Pull request closed without merging**
