### PR TITLE
Arthur-Nitzz_zkThon Completed

### PR DESCRIPTION
**Pull request by Arthur-Nitzz**
This pull request is for the zkEVM Challenge 2. I have reviewed the zkEVM documentation and shared my understanding through a Twitter thread using the hashtags #zkThon and #zkEVM. The link to my Twitter thread is [insert link here].

## Checklist

- [x] I have created a new file named `solution-2.md` for this challenge.
- [x] I have added the details of my submission to the [Airtable form](https://airtable.com/shr21z0FfPImZfYBQ).
- [x] I have named my branch `Arthur-Nitzz_zkthon`.

### CODE REVIEW

**Comment by Arthur-Nitzz** [comment]
https://testnet-zkevm.polygonscan.com/address/0x29d7739d711c14cf119697d3439b0e411522a68b

**Review by PriyathamVarma — CHANGES_REQUESTED** [review]
Could you please paste the deployed contract address. Thank you.

**Comment by megabyte0x** [comment]
Please name your branch correctly.

Check out the guidelines here => https://github.com/Polygon-Advocates/zkThon-2023/blob/main/pull_request_template.md

Thanks

**Comment by Arthur-Nitzz** [comment]
> Please name your branch correctly.
> 
> Check out the guidelines here => https://github.com/Polygon-Advocates/zkThon-2023/blob/main/pull_request_template.md
> 
> Thanks

Hey, the branch name is according to the templete username_zkThon

**Pull request closed without merging**
