### PR TITLE
Create solution-1.md

### PR DESCRIPTION
**Pull request by Parth0x108**
Challenge 1 :- Added the twitter thread link.

## Description

This pull request is for the zkEVM Challenge 1. I have reviewed the zkEVM documentation and shared my understanding through a Twitter thread using the hashtags #zkThon and #zkEVM. The link to my Twitter thread is [insert link here].

## Checklist

- [ ] I have created a new file named `solution-1.md` for this challenge.
- [ ] I have added the details of my submission to the [Airtable form](https://airtable.com/shr21z0FfPImZfYBQ).
- [ ] I have named my branch `username_zkthon`.

### CODE REVIEW

**Comment by Parthmandale** [comment]
Hey I have submitted first challenge solution, pls do accept the PR.

**Review by PriyathamVarma — APPROVED** [review]
what a lovely thread in twitter ser.

**Comment by Parthmandale** [comment]
Thanks sir, will try 2nd and 3rd solution as well!

**Comment by Parth0x108** [comment]
sir i'm done with challenge 2 please accept the pr.

**Pull request closed without merging**
